development:
#  adapter: sqlite3
  adapter: mysql
  host: <%= ENV['MYSQL_HOST'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
  encoding: utf8
  pool: 200
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

test:
#  adapter: sqlite3
  adapter: mysql
  host: <%= ENV['MYSQL_HOST'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: <%= ENV['MYSQL_SOCKET'] %>
  encoding: utf8
  pool: 200
  database: db/test.sqlite3
  pool: 5
  timeout: 5000


