# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b1c81106cdf73d8862e098894138dc83fb95687d5547f228a0faf46b69d8380924fcc1d616f09693185f58002a384381760de95cbf040a6ee3c201d47ead940

test:
  secret_key_base: 7e03b510ba60a9e2b4ff22f72dd6d674e1d8393fa07989f2db5301296e125f0e73703b6eaad9a52dbc7fa77be98a03403606a5898580d270da210cc0dc6e5b11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
